jobs:
  allowlist:
    name: Anti Virus Allowlisting
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download file
      run: 'curl --remote-name ${{ inputs.url }} -L

        '
    - continue-on-error: true
      name: Upload to Kaspersky
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        password: ${{ secrets.ALLOWLIST_KASPERSKY_PASSWORD }}
        port: 990
        protocol: ftps
        server: allowlist.kaspersky-labs.com
        username: ${{ secrets.ALLOWLIST_KASPERSKY_USERNAME }}
    - continue-on-error: true
      name: Upload to Avast
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        password: ${{ secrets.ALLOWLIST_AVAST_PASSWORD }}
        port: 21
        protocol: ftp
        server: whitelisting.avast.com
        username: ${{ secrets.ALLOWLIST_AVAST_USERNAME }}
name: AntiVirus Whitelisting
on:
  repository_dispatch:
    types: trigger-ga___av-whitelist.yml
