defaults:
  run:
    shell: bash
env:
  JAVA_DIST: zulu
  JAVA_VERSION: 22
jobs:
  test:
    name: Compile and Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: ${{ env.JAVA_DIST }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Build and Test
      run: 'xvfb-run mvn -B verify jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Pcoverage -Dsonar.projectKey=cryptomator_cryptomator -Dsonar.organization=cryptomator
        -Dsonar.host.url=https://sonarcloud.io

        '
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/')
      name: Draft a release
      uses: softprops/action-gh-release@v2
      with:
        body: ":construction: Work in Progress\n\n\u23F3 Please be patient, the builds\
          \ are still [running](https://github.com/cryptomator/cryptomator/actions).\
          \ New versions of Cryptomator can be found here in a few moments. \u23F3\
          \n\nAs usual, the GPG signatures can be checked using [our public key `5811\
          \ 7AFA 1F85 B3EE C154  677D 615D 449F E6E6 A235`](https://gist.github.com/cryptobot/211111cf092037490275f39d408f461a).\n\
          \n---\n<!-- Don't forget to include the \U0001F4BE SHA-256 checksums of\
          \ release artifacts: -->"
        discussion_category_name: releases
        draft: true
        generate_release_notes: true
        token: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
