env:
  JDK_VENDOR: zulu
  JDK_VERSION: 22.0.1+8
jobs:
  jdk-current:
    name: Check out current version
    outputs:
      jdk-date: ${{ steps.get-data.outputs.jdk-date}}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        check-latest: false
        distribution: ${{ env.JDK_VENDOR }}
        java-version: ${{ env.JDK_VERSION }}
    - continue-on-error: true
      id: get-data
      name: Read JAVA_VERSION_DATE and store in env variable
      run: 'date=$(cat ${JAVA_HOME}/release | grep "JAVA_VERSION_DATE=\"" | awk -F''=''
        ''{print $2}'' | tr -d ''"'')

        echo "jdk-date=${date}" >> "$GITHUB_OUTPUT"

        '
  jdk-latest:
    name: Checkout latest jdk version
    outputs:
      jdk-date: ${{ steps.get-data.outputs.jdk-date}}
      jdk-version: ${{ steps.get-data.outputs.jdk-version}}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: ${{ env.JDK_VENDOR }}
        java-version: 21
    - continue-on-error: true
      id: get-data
      name: Read JAVA_VERSION_DATE and store in env variable
      run: 'date=$(cat ${JAVA_HOME}/release | grep "JAVA_VERSION_DATE=\"" | awk -F''=''
        ''{print $2}'' | tr -d ''"'')

        echo "jdk-date=${date}" >> "$GITHUB_OUTPUT"

        version=$(cat ${JAVA_HOME}/release | grep "JAVA_RUNTIME_VERSION=\"" | awk
        -F''='' ''{print $2}'' | tr -d ''"'')

        echo "jdk-version=${version}" >> "$GITHUB_OUTPUT"

        '
  notify:
    if: ${{ needs.jdk-latest.outputs.jdk-date }} > ${{ needs.jdk-current.outputs.jdk-date
      }}
    name: Notifies for jdk update
    needs:
    - jdk-current
    - jdk-latest
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        MSG_MINIMAL: true
        SLACK_CHANNEL: cryptomator-desktop
        SLACK_FOOTER: false
        SLACK_ICON: false
        SLACK_ICON_EMOJI: ':bot:'
        SLACK_MESSAGE: Cryptomator-CI JDK can be upgraded to ${{ needs.jdk-latest.outputs.jdk-version
          }}. See https://github.com/cryptomator/cryptomator/wiki/How-to-update-the-build-JDK
          for instructions.
        SLACK_TITLE: JDK update available
        SLACK_USERNAME: Cryptobot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
name: Checks JDK version for minor updates
on:
  repository_dispatch:
    types: trigger-ga___check-jdk-updates.yml
