jobs:
  check-dependencies:
    secrets:
      nvd-api-key: ${{ secrets.NVD_API_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
    uses: skymatic/workflows/.github/workflows/run-dependency-check.yml@v1
    with:
      java-distribution: temurin
      java-version: 22
      runner-os: ubuntu-latest
name: OWASP Maven Dependency Check
on:
  repository_dispatch:
    types: trigger-ga___dependency-check.yml
