jobs:
  update-error-db:
    if: github.event.discussion.category.name == 'Errors'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: query-data
      if: github.event_name == 'discussion_comment' || github.event_name == 'discussion'
        && github.event.action != 'deleted'
      name: Query Discussion Data
      uses: actions/github-script@v7
      with:
        script: "const query = `query ($owner: String!, $name: String!, $discussionNumber:\
          \ Int!) {\n  repository(owner: $owner, name: $name) {\n    discussion(number:\
          \ $discussionNumber) {\n      id\n      upvoteCount\n      title\n     \
          \ url\n      answer {\n        url\n        upvoteCount\n      }\n     \
          \ comments {\n        totalCount\n      }\n    }\n  }\n}`;\nconst variables\
          \ = {\n  owner: context.repo.owner,\n  name: context.repo.repo,\n  discussionNumber:\
          \ context.payload.discussion.number\n}\nreturn await github.graphql(query,\
          \ variables)\n"
    - continue-on-error: true
      id: get-gist
      name: Get Gist
      uses: andymckay/get-gist-action@master
      with:
        gistURL: https://gist.github.com/cryptobot/accba9fb9555e7192271b85606f97230
    - continue-on-error: true
      env:
        DISCUSSION: ${{ steps.query-data.outputs.result }}
      name: Merge Error Code Data
      run: "jq -c '.' ${{ steps.get-gist.outputs.file }} > original.json\nif [ ! -z\
        \ \"$DISCUSSION\" ]\nthen\n  echo $DISCUSSION | jq -c '.repository.discussion\
        \ | .comments = .comments.totalCount | {(.id|tostring) : .}' > new.json\n\
        \  jq -s '.[0] * .[1]' original.json new.json > merged.json\nelse\n  cat original.json\
        \ | jq 'del(.[] | select(.url==\"https://github.com/cryptomator/cryptomator/discussions/${{\
        \ github.event.discussion.number }}\"))' > merged.json\nfi\n"
    - continue-on-error: true
      name: Patch Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        file_path: merged.json
        gist_file_name: errorcodes.json
        gist_id: accba9fb9555e7192271b85606f97230
        token: ${{ secrets.CRYPTOBOT_GIST_TOKEN }}
name: Update Error Database
on:
  repository_dispatch:
    types: trigger-ga___error-db.yml
