env:
  JAVA_DIST: zulu
  JAVA_VERSION: 22
jobs:
  determine-version:
    name: Determines the version following semver
    outputs:
      revNum: ${{ steps.versions.outputs.revNum }}
      semVerNum: ${{ steps.versions.outputs.semVerNum }}
      semVerStr: ${{ steps.versions.outputs.semVerStr }}
      type: ${{ steps.versions.outputs.type}}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: ${{ env.JAVA_DIST }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      id: versions
      name: Get version information
      run: "if [[ $GITHUB_REF =~ refs/tags/[0-9]+\\.[0-9]+\\.[0-9]+.* ]]; then\n \
        \ SEM_VER_STR=${GITHUB_REF##*/}\nelif [[ \"${{ inputs.version }}\" =~ [0-9]+\\\
        .[0-9]+\\.[0-9]+.* ]]; then\n  SEM_VER_STR=\"${{ inputs.version }}\"\nelse\n\
        \  SEM_VER_STR=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`\n\
        fi\nSEM_VER_NUM=`echo ${SEM_VER_STR} | sed -E 's/([0-9]+\\.[0-9]+\\.[0-9]+).*/\\\
        1/'`\nREVCOUNT=`git rev-list --count HEAD`\nTYPE=\"unknown\"\nif [[ $SEM_VER_STR\
        \ =~ [0-9]+\\.[0-9]+\\.[0-9]+$ ]]; then\n  TYPE=\"stable\"\nelif [[ $SEM_VER_STR\
        \ =~ [0-9]+\\.[0-9]+\\.[0-9]+-alpha[1-9]+$ ]]; then\n  TYPE=\"alpha\"\nelif\
        \ [[ $SEM_VER_STR =~ [0-9]+\\.[0-9]+\\.[0-9]+-beta[1-9]+$ ]]; then\n  TYPE=\"\
        beta\"\nelif [[ $SEM_VER_STR =~ [0-9]+\\.[0-9]+\\.[0-9]+-rc[1-9]$ ]]; then\n\
        \  TYPE=\"rc\"\nfi\necho \"semVerStr=${SEM_VER_STR}\" >> $GITHUB_OUTPUT\n\
        echo \"semVerNum=${SEM_VER_NUM}\" >> $GITHUB_OUTPUT\necho \"revNum=${REVCOUNT}\"\
        \ >> $GITHUB_OUTPUT\necho \"type=${TYPE}\" >> $GITHUB_OUTPUT\n"
    - continue-on-error: true
      name: Validate Version
      uses: skymatic/semver-validation-action@v3
      with:
        version: ${{ steps.versions.outputs.semVerStr }}
name: Parse and Validate a version string or tag
on:
  repository_dispatch:
    types: trigger-ga___get-version.yml
