jobs:
  get-version:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download source tarball
      run: 'curl -L -H "Accept: application/vnd.github+json" https://github.com/cryptomator/cryptomator/archive/refs/tags/${{
        github.event.release.tag_name }}.tar.gz --output cryptomator-${{ github.event.release.tag_name
        }}.tar.gz

        '
    - continue-on-error: true
      env:
        GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
        GPG_PRIVATE_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
      name: Sign source tarball with key 615D449FE6E6A235
      run: 'echo "${GPG_PRIVATE_KEY}" | gpg --batch --quiet --import

        echo "${GPG_PASSPHRASE}" | gpg --batch --quiet --passphrase-fd 0 --pinentry-mode
        loopback -u 615D449FE6E6A235 --detach-sign -a cryptomator-*.tar.gz

        '
    - continue-on-error: true
      name: Publish asc on GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        files: 'cryptomator-*.tar.gz.asc

          '
        token: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
    - continue-on-error: true
      env:
        MSG_MINIMAL: true
        SLACK_CHANNEL: cryptomator-desktop
        SLACK_FOOTER: false
        SLACK_ICON: false
        SLACK_ICON_EMOJI: ':bot:'
        SLACK_MESSAGE: Ready to <https://github.com/${{ github.repository }}/actions/workflows/debian.yml|build
          deb Package>.
        SLACK_TITLE: Release ${{ github.event.repository.name }} ${{ github.event.release.tag_name
          }} published.
        SLACK_USERNAME: Cryptobot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
name: Post Release Publish Tasks
on:
  repository_dispatch:
    types: trigger-ga___post-publish.yml
