defaults:
  run:
    shell: bash
env:
  JAVA_DIST: zulu
  JAVA_VERSION: 22
jobs:
  test:
    if: '!contains(github.event.head_commit.message, ''[ci skip]'') && !contains(github.event.head_commit.message,
      ''[skip ci]'')'
    name: Compile and Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: ${{ env.JAVA_DIST }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Build and Test
      run: xvfb-run mvn -B clean install jacoco:report -Pcoverage
name: Pull Request
on:
  repository_dispatch:
    types: trigger-ga___pullrequest.yml
