defaults:
  run:
    shell: bash
env:
  JAVA_DIST: zulu
  JAVA_VERSION: 22
jobs:
  check-preconditions:
    name: Validate commits pushed to release/hotfix branch to fulfill release requirements
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: ${{ env.JAVA_DIST }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      id: validate-pom-version
      name: Validate POM version
      run: "if [[ $GITHUB_REF =~ refs/heads/(hotfix|release)/[0-9]+\\.[0-9]+\\.[0-9]+.*\
        \ ]]; then\n  SEM_VER_STR=${GITHUB_REF##*/}\nelse\n  echo \"Failed to parse\
        \ version\"\n  exit 1\nfi\n\nif [[ ${SEM_VER_STR} == `mvn help:evaluate -Dexpression=project.version\
        \ -q -DforceStdout` ]]; then\n  echo \"semVerStr=${SEM_VER_STR}\" >> $GITHUB_OUTPUT\n\
        else\n  echo \"Version not set in POM\"\n  exit 1\nfi\n"
    - continue-on-error: true
      name: Validate release in org.cryptomator.Cryptomator.metainfo.xml file
      run: "if ! grep -q \"<release date=\\\".*\\\" version=\\\"${{ steps.validate-pom-version.outputs.semVerStr\
        \ }}\\\">\" dist/linux/common/org.cryptomator.Cryptomator.metainfo.xml; then\n\
        \  echo \"Release not set in dist/linux/common/org.cryptomator.Cryptomator.metainfo.xml\"\
        \n  exit 1\nfi\n"
    - continue-on-error: true
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
      name: Cache NVD DB
      uses: actions/cache@v4
      with:
        key: dependency-check-${{ github.run_id }}
        path: ~/.m2/repository/org/owasp/dependency-check-data/
        restore-keys: 'dependency-check

          '
    - continue-on-error: true
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      id: dependency-check
      name: Run org.owasp:dependency-check plugin
      run: mvn -B verify -Pdependency-check -DskipTests
name: Release Check
on:
  repository_dispatch:
    types: trigger-ga___release-check.yml
