jobs:
  winget:
    name: Publish winget package
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.CRYPTOBOT_WINGET_TOKEN }}
      name: Sync winget-pkgs fork
      run: 'gh repo sync cryptomator/winget-pkgs -b master --force

        '
    - continue-on-error: true
      name: Submit package
      uses: vedantmgoyal2009/winget-releaser@v2
      with:
        identifier: Cryptomator.Cryptomator
        installers-regex: \.msi$
        release-tag: ${{ inputs.tag }}
        token: ${{ secrets.CRYPTOBOT_WINGET_TOKEN }}
        version: ${{ inputs.tag }}
name: Publish  MSI to winget-pkgs
on:
  repository_dispatch:
    types: trigger-ga___winget.yml
